import type { Machine, ProductSizeCategory } from './types';

export const MACHINES: Machine[] = [
  {
    id: 'alphashot-micro-v2',
    nom: 'Alphashot Micro Pro v2',
    prix: 15450,
    capaciteJour: 200,
    tailleMax: '16×18×15 cm',
    poidsMax: '1 kg',
    tailleCategories: ['petit'],
    useCases: ['Bijoux', 'Montres', 'Petits objets de luxe', 'Cosmétiques'],
    maintenanceAnnuelle: 927,   // 6%
    consommablesAnnuels: 500,
  },
  {
    id: 'alphashot-360',
    nom: 'Alphashot 360',
    prix: 15000,
    capaciteJour: 200,
    tailleMax: '30×30×30 cm',
    poidsMax: '3 kg',
    tailleCategories: ['petit', 'moyen'],
    useCases: ['Vues 360°', 'E-commerce interactif', 'Catalogues'],
    maintenanceAnnuelle: 900,
    consommablesAnnuels: 500,
  },
  {
    id: 'alphashot-g2',
    nom: 'Alphashot G2',
    prix: 15450,
    capaciteJour: 200,
    tailleMax: '30×30×30 cm',
    poidsMax: '3 kg',
    tailleCategories: ['petit', 'moyen'],
    useCases: ['Chaussures', 'Maroquinerie', 'Cosmétiques', 'Électronique'],
    maintenanceAnnuelle: 927,
    consommablesAnnuels: 500,
  },
  {
    id: 'alphashot-pro-g2',
    nom: 'Alphashot Pro G2',
    prix: 20450,
    capaciteJour: 200,
    tailleMax: '40×40×40 cm',
    poidsMax: '5 kg',
    tailleCategories: ['petit', 'moyen'],
    useCases: ['Packshots pro haute qualité', 'E-commerce premium'],
    maintenanceAnnuelle: 1227,
    consommablesAnnuels: 500,
  },
  {
    id: 'alphashot-xl-v2',
    nom: 'Alphashot XL v2',
    prix: 18950,
    capaciteJour: 200,
    tailleMax: '60×60×100 cm',
    poidsMax: '30 kg',
    tailleCategories: ['moyen', 'grand'],
    useCases: ['Mobilier petit', 'Équipements sportifs', 'Électroménager'],
    maintenanceAnnuelle: 1137,
    consommablesAnnuels: 500,
  },
  {
    id: 'alphashot-xl-wine-v2',
    nom: 'Alphashot XL Wine v2',
    prix: 20450,
    capaciteJour: 200,
    tailleMax: 'Bouteilles vin/spiritueux',
    poidsMax: '5 kg',
    tailleCategories: ['moyen'],
    useCases: ['Vins', 'Spiritueux', 'Bouteilles'],
    maintenanceAnnuelle: 1227,
    consommablesAnnuels: 500,
  },
  {
    id: 'alphashot-xl-pro-v2',
    nom: 'Alphashot XL Pro v2',
    prix: 22450,
    capaciteJour: 200,
    tailleMax: '60×60×100 cm',
    poidsMax: '30 kg',
    tailleCategories: ['moyen', 'grand'],
    useCases: ['Version Pro du XL', 'Éclairage avancé', 'Haute qualité'],
    maintenanceAnnuelle: 1347,
    consommablesAnnuels: 500,
  },
  {
    id: 'alphastudio-compact-v2',
    nom: 'Alphastudio Compact Pro v2',
    prix: 36350,
    capaciteJour: 180,
    tailleMax: '80×80×120 cm',
    poidsMax: '50 kg',
    tailleCategories: ['grand'],
    useCases: ['Mobilier moyen', 'Équipements grands formats'],
    maintenanceAnnuelle: 2181,
    consommablesAnnuels: 800,
  },
  {
    id: 'alphastudio-xxl-v2',
    nom: 'Alphastudio XXL Pro v2',
    prix: 45450,
    capaciteJour: 150,
    tailleMax: '150×150×200 cm',
    poidsMax: '200 kg',
    tailleCategories: ['grand', 'tres-grand'],
    useCases: ['Mobilier grand format', 'Vélos', 'Objets volumineux'],
    maintenanceAnnuelle: 2727,
    consommablesAnnuels: 1000,
  },
  {
    id: 'fashion-studio-basic',
    nom: 'Fashion Studio Basic',
    prix: 56450,
    capaciteJour: 80,
    tailleMax: 'Mannequin taille réelle',
    poidsMax: 'N/A',
    tailleCategories: ['grand', 'tres-grand'],
    useCases: ['Vêtements portés (version simplifiée)'],
    maintenanceAnnuelle: 3387,
    consommablesAnnuels: 1200,
  },
  {
    id: 'fashion-studio',
    nom: 'Fashion Studio Pro v2',
    prix: 84450,
    capaciteJour: 100,
    tailleMax: 'Mannequin taille réelle',
    poidsMax: 'N/A',
    tailleCategories: ['grand', 'tres-grand'],
    useCases: ['Vêtements portés', 'Mode', 'Accessoires portés'],
    maintenanceAnnuelle: 5067,
    consommablesAnnuels: 1500,
  },
  {
    id: 'bike-studio',
    nom: 'Bike Studio',
    prix: 89450,
    capaciteJour: 80,
    tailleMax: 'Vélos complets',
    poidsMax: '30 kg',
    tailleCategories: ['tres-grand'],
    useCases: ['Cycles', 'Vélos', 'Trottinettes'],
    maintenanceAnnuelle: 5367,
    consommablesAnnuels: 1200,
  },
  {
    id: 'furniture-studio',
    nom: 'Furniture Studio',
    prix: 119450,
    capaciteJour: 60,
    tailleMax: 'Mobilier XXL',
    poidsMax: '500 kg',
    tailleCategories: ['tres-grand'],
    useCases: ['Canapés', 'Lits', 'Mobilier grande taille'],
    maintenanceAnnuelle: 7167,
    consommablesAnnuels: 2000,
  },
];

// Fonction helper pour trouver une machine par ID
export function getMachineById(id: string): Machine | undefined {
  return MACHINES.find(m => m.id === id);
}

// Fonction helper pour filtrer les machines par catégorie de taille
export function getMachinesBySize(category: ProductSizeCategory): Machine[] {
  return MACHINES.filter(m => m.tailleCategories.includes(category));
}
