import type { Machine, ProductSizeCategory } from './types';

/**
 * Base de données des machines Orbitvu
 * Source de vérité : Analyse Gemini des brochures + recherches complémentaires
 * Maintenance annuelle = 0€ pour toutes les machines
 */
export const MACHINES: Machine[] = [
  // ============================================
  // PETITS PRODUITS (< 30cm)
  // ============================================
  {
    id: 'alphashot-micro-v2',
    nom: 'Alphashot Micro Pro v2',
    prix: 15450,
    capaciteJour: 200,
    tailleMax: '18×15×16 cm',
    poidsMax: '1 kg',
    tailleCategories: ['petit'],
    useCases: ['Bijoux', 'Montres', 'Pierres précieuses', 'Pièces de monnaie', 'Petits composants'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 500,
    dimensionsMax: { l: 18, w: 15, h: 16 },
    poidsMaxKg: 1,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['jewelry', 'cosmetics'],
    volumeRange: { min: 1000, max: 50000 },
    keyAdvantages: [
      { fr: 'Élimination automatique de l\'arrière-plan avec IQ Mask', en: 'Automatic background removal with IQ Mask' },
      { fr: 'Éclairage spécialisé pour faire briller les produits (bijoux/pierres)', en: 'Specialized lighting to make products shine (jewelry/gems)' },
      { fr: 'Macro et Super Focus pour les détails', en: 'Macro and Super Focus for details' },
    ],
    limitations: [
      { fr: 'Limité aux très petits objets (< 1kg)', en: 'Limited to very small objects (< 1kg)' },
    ],
    spaceRequired: 'Bureau',
    studioFootprint: { l: 83, w: 52, h: 72 },
  },
  {
    id: 'alphashot-360',
    nom: 'Alphashot 360',
    prix: 15000,
    capaciteJour: 200,
    tailleMax: '30×30×30 cm',
    poidsMax: '3 kg',
    tailleCategories: ['petit', 'moyen'],
    useCases: ['Lunettes', 'Petits appareils électroniques', 'Cosmétiques', 'Chaussures (petites)'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 500,
    dimensionsMax: { l: 30, w: 30, h: 30 },
    poidsMaxKg: 3,
    features: ['packshot', '360'],
    automationLevel: 'full-auto',
    idealSectors: ['cosmetics', 'electronics', 'general'],
    volumeRange: { min: 500, max: 15000 },
    keyAdvantages: [
      { fr: 'Photos web prêtes en quelques secondes', en: 'Web-ready photos in seconds' },
      { fr: 'Portes sur deux côtés pour accès facile', en: 'Doors on both sides for easy access' },
      { fr: 'Ajustement rapide de la position caméra', en: 'Quick camera position adjustment' },
    ],
    limitations: [
      { fr: 'Poids limité à 3kg, non adapté aux objets lourds', en: 'Weight limited to 3kg, not suitable for heavy objects' },
    ],
    spaceRequired: 'Bureau',
    studioFootprint: { l: 115, w: 69, h: 64 },
  },
  {
    id: 'alphashot-g2',
    nom: 'Alphashot G2',
    prix: 15450,
    capaciteJour: 200,
    tailleMax: '30×30×30 cm',
    poidsMax: '3 kg',
    tailleCategories: ['petit', 'moyen'],
    useCases: ['Chaussures', 'Maroquinerie', 'Cosmétiques', 'Électronique'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 500,
    dimensionsMax: { l: 30, w: 30, h: 30 },
    poidsMaxKg: 3,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['footwear', 'bags', 'cosmetics', 'electronics'],
    volumeRange: { min: 1000, max: 20000 },
    keyAdvantages: [
      { fr: 'Nouvelle génération de l\'Alphashot 360', en: 'New generation of Alphashot 360' },
      { fr: 'Éclairage LED amélioré', en: 'Improved LED lighting' },
      { fr: 'Interface logicielle modernisée', en: 'Modernized software interface' },
    ],
    limitations: [
      { fr: 'Poids limité à 3kg', en: 'Weight limited to 3kg' },
    ],
    spaceRequired: 'Bureau',
    studioFootprint: { l: 115, w: 69, h: 64 },
  },
  {
    id: 'alphashot-pro-g2',
    nom: 'Alphashot Pro G2',
    prix: 20450,
    capaciteJour: 250,
    tailleMax: '35×35×40 cm',
    poidsMax: '10 kg',
    tailleCategories: ['petit', 'moyen'],
    useCases: ['Produits réfléchissants/transparents', 'Cosmétiques', 'Électronique'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 500,
    dimensionsMax: { l: 35, w: 35, h: 40 },
    poidsMaxKg: 10,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['cosmetics', 'electronics', 'general'],
    volumeRange: { min: 5000, max: 60000 },
    keyAdvantages: [
      { fr: 'Premier studio photo IA au monde (détection auto des réglages)', en: 'World\'s first AI photo studio (auto settings detection)' },
      { fr: 'Productivité extrême (250 produits/jour)', en: 'Extreme productivity (250 products/day)' },
      { fr: '74 sources lumineuses pour objets complexes', en: '74 light sources for complex objects' },
    ],
    limitations: [
      { fr: 'Taille produit limitée (intermédiaire)', en: 'Limited product size (intermediate)' },
    ],
    spaceRequired: 'Sol/Table robuste',
    studioFootprint: { l: 112, w: 71, h: 72 },
  },

  // ============================================
  // PRODUITS MOYENS (30-60cm)
  // ============================================
  {
    id: 'alphashot-xl-v2',
    nom: 'Alphashot XL v2',
    prix: 18950,
    capaciteJour: 200,
    tailleMax: '50×30×70 cm',
    poidsMax: '25 kg',
    tailleCategories: ['moyen', 'grand'],
    useCases: ['Chaussures', 'Sacs', 'Jouets', 'Électronique'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 500,
    dimensionsMax: { l: 50, w: 30, h: 70 },
    poidsMaxKg: 25,
    features: ['packshot', '360', 'video'],
    automationLevel: 'semi-auto',
    idealSectors: ['footwear', 'bags', 'electronics', 'general'],
    volumeRange: { min: 1000, max: 30000 },
    keyAdvantages: [
      { fr: 'Polyvalence pour produits moyens (sacs, chaussures)', en: 'Versatility for medium products (bags, shoes)' },
      { fr: 'Kit suspension disponible en option', en: 'Suspension kit available as option' },
      { fr: 'Support multi-caméras (jusqu\'à 5)', en: 'Multi-camera support (up to 5)' },
    ],
    limitations: [
      { fr: 'Non adapté pour mannequins vivants ou gros mobilier', en: 'Not suitable for live mannequins or large furniture' },
    ],
    spaceRequired: 'Sol',
    studioFootprint: { l: 142, w: 87, h: 176 },
  },
  {
    id: 'alphashot-xl-wine-v2',
    nom: 'Alphashot XL Wine v2',
    prix: 20450,
    capaciteJour: 200,
    tailleMax: 'Bouteilles vin/spiritueux',
    poidsMax: '5 kg',
    tailleCategories: ['moyen'],
    useCases: ['Vins', 'Spiritueux', 'Bouteilles'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 500,
    dimensionsMax: { l: 40, w: 40, h: 50 },
    poidsMaxKg: 5,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['wine'],
    volumeRange: { min: 1000, max: 25000 },
    keyAdvantages: [
      { fr: 'Spécialisé pour bouteilles et étiquettes', en: 'Specialized for bottles and labels' },
      { fr: 'Éclairage optimisé pour le verre', en: 'Lighting optimized for glass' },
      { fr: 'Rendu parfait des reflets', en: 'Perfect reflection rendering' },
    ],
    limitations: [
      { fr: 'Spécialisé vins/spiritueux uniquement', en: 'Specialized for wine/spirits only' },
    ],
    spaceRequired: 'Sol',
    studioFootprint: { l: 142, w: 87, h: 176 },
  },
  {
    id: 'alphashot-xl-pro-v2',
    nom: 'Alphashot XL Pro v2',
    prix: 22450,
    capaciteJour: 200,
    tailleMax: '50×70×30 cm',
    poidsMax: '25 kg',
    tailleCategories: ['moyen', 'grand'],
    useCases: ['Version Pro du XL', 'Éclairage avancé', 'Haute qualité'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 500,
    dimensionsMax: { l: 50, w: 70, h: 30 },
    poidsMaxKg: 25,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['footwear', 'bags', 'electronics', 'general'],
    volumeRange: { min: 5000, max: 40000 },
    keyAdvantages: [
      { fr: 'Version Pro avec éclairages coulissants pour contrôle précis', en: 'Pro version with sliding lights for precise control' },
      { fr: 'Laser de centrage et portes coulissantes des deux côtés', en: 'Centering laser and sliding doors on both sides' },
      { fr: 'Contrôle jusqu\'à 5 caméras simultanément', en: 'Control up to 5 cameras simultaneously' },
    ],
    limitations: [
      { fr: 'Coût plus élevé que le XL standard', en: 'Higher cost than standard XL' },
    ],
    spaceRequired: 'Sol',
    studioFootprint: { l: 142, w: 87, h: 176 },
  },

  // ============================================
  // FLAT-LAY (Vue de dessus)
  // ============================================
  {
    id: 'alphadesk',
    nom: 'Alphadesk',
    prix: 18000,
    capaciteJour: 480,
    tailleMax: '85×70×5 cm',
    poidsMax: '10 kg',
    tailleCategories: ['petit', 'moyen'],
    useCases: ['Vêtements à plat', 'Tissus', 'Accessoires', 'Petits objets plats'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 400,
    dimensionsMax: { l: 85, w: 70, h: 5 },
    poidsMaxKg: 10,
    features: ['packshot', 'flat-lay', 'video'],
    automationLevel: 'semi-auto',
    idealSectors: ['fashion', 'general'],
    volumeRange: { min: 2000, max: 50000 },
    keyAdvantages: [
      { fr: 'Détourage immédiat pour le textile à plat', en: 'Immediate clipping for flat textiles' },
      { fr: 'Boutons de capture instantanée physiques pour rapidité', en: 'Physical instant capture buttons for speed' },
      { fr: 'Outils Ghost image pour alignement parfait', en: 'Ghost image tools for perfect alignment' },
    ],
    limitations: [
      { fr: 'Limité à la 2D (vue de dessus uniquement)', en: 'Limited to 2D (top-down view only)' },
      { fr: 'Hauteur produit max 5cm', en: 'Max product height 5cm' },
    ],
    spaceRequired: 'Bureau',
    studioFootprint: { l: 137, w: 123, h: 155 },
  },
  {
    id: 'alphatable',
    nom: 'Alphatable',
    prix: 35000,
    capaciteJour: 500,
    tailleMax: '165×112×5 cm',
    poidsMax: '80 kg',
    tailleCategories: ['moyen', 'grand'],
    useCases: ['Grands vêtements', 'Tapis', 'Carrelage', 'Tissus grands formats'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 600,
    dimensionsMax: { l: 165, w: 112, h: 5 },
    poidsMaxKg: 80,
    features: ['packshot', 'flat-lay', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['fashion', 'furniture', 'general'],
    volumeRange: { min: 5000, max: 100000 },
    keyAdvantages: [
      { fr: 'Grand format pour vêtements complets (manteaux, robes)', en: 'Large format for complete garments (coats, dresses)' },
      { fr: 'Guidage laser pour positionnement précis', en: 'Laser guidance for precise positioning' },
      { fr: 'Zoom motorisé via logiciel', en: 'Motorized zoom via software' },
    ],
    limitations: [
      { fr: 'Limité à la 2D (vue de dessus uniquement)', en: 'Limited to 2D (top-down view only)' },
      { fr: 'Encombrement au sol important', en: 'Significant floor space required' },
    ],
    spaceRequired: 'Sol',
    studioFootprint: { l: 338, w: 191, h: 268 },
  },

  // ============================================
  // GRANDS PRODUITS (60-150cm)
  // ============================================
  {
    id: 'alphastudio-compact-v2',
    nom: 'Alphastudio Compact Pro v2',
    prix: 36350,
    capaciteJour: 180,
    tailleMax: '100×70×190 cm',
    poidsMax: '100 kg',
    tailleCategories: ['grand'],
    useCases: ['Valises', 'Petits meubles', 'Sacs', 'Outils'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 800,
    dimensionsMax: { l: 100, w: 70, h: 190 },
    poidsMaxKg: 100,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['bags', 'furniture', 'sports', 'general'],
    volumeRange: { min: 5000, max: 40000 },
    keyAdvantages: [
      { fr: 'Flexibilité pour objets moyens à gros (jusqu\'à la valise)', en: 'Flexibility for medium to large objects (up to suitcase)' },
      { fr: 'Magic Table pour suspendre les objets sans fond visible', en: 'Magic Table to suspend objects without visible background' },
      { fr: 'Charge admissible élevée (100kg)', en: 'High load capacity (100kg)' },
    ],
    limitations: [
      { fr: 'Hauteur un peu juste pour mannequins vivants adultes', en: 'Height a bit limited for adult live mannequins' },
    ],
    spaceRequired: 'Studio',
    studioFootprint: { l: 178, w: 136, h: 183 },
  },
  {
    id: 'alphastudio-xxl-v2',
    nom: 'Alphastudio XXL Pro v2',
    prix: 45450,
    capaciteJour: 150,
    tailleMax: '100×70×190 cm',
    poidsMax: '100 kg',
    tailleCategories: ['grand', 'tres-grand'],
    useCases: ['Mannequins vivants', 'Vêtements (Ghost)', 'Gros bagages', 'Meubles'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 1000,
    dimensionsMax: { l: 100, w: 70, h: 190 },
    poidsMaxKg: 100,
    features: ['packshot', '360', 'video', 'ghost-mannequin', 'lifestyle'],
    automationLevel: 'full-auto',
    idealSectors: ['fashion', 'furniture', 'general'],
    volumeRange: { min: 15000, max: 80000 },
    keyAdvantages: [
      { fr: 'Solution tout-en-un pour la mode (plat, ghost, porté)', en: 'All-in-one solution for fashion (flat, ghost, worn)' },
      { fr: 'Éclairage LED surdimensionné pour qualité impression', en: 'Oversized LED lighting for print quality' },
      { fr: 'Détourage automatique même pour modèles', en: 'Automatic clipping even for models' },
    ],
    limitations: [
      { fr: 'IQ-Mask parfois imparfait sur modèles en mouvement', en: 'IQ-Mask sometimes imperfect on moving models' },
    ],
    spaceRequired: 'Grand Studio',
    studioFootprint: { l: 277, w: 190, h: 273 },
  },

  // ============================================
  // TRÈS GRANDS PRODUITS (> 150cm)
  // ============================================
  {
    id: 'fashion-studio-basic',
    nom: 'Fashion Studio Basic',
    prix: 56450,
    capaciteJour: 80,
    tailleMax: 'Mannequin taille réelle',
    poidsMax: 'N/A',
    tailleCategories: ['grand', 'tres-grand'],
    useCases: ['Mode portée (version simplifiée)'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 1200,
    dimensionsMax: { l: 200, w: 100, h: 200 },
    poidsMaxKg: 0,
    features: ['packshot', '360', 'video', 'ghost-mannequin', 'lifestyle'],
    automationLevel: 'semi-auto',
    idealSectors: ['fashion'],
    volumeRange: { min: 5000, max: 30000 },
    keyAdvantages: [
      { fr: 'Studio dédié à la mode à prix d\'entrée', en: 'Dedicated fashion studio at entry price' },
      { fr: 'Conçu pour mannequins humains', en: 'Designed for human models' },
    ],
    limitations: [
      { fr: 'Version simplifiée sans miroir virtuel', en: 'Simplified version without virtual mirror' },
      { fr: 'Moins de fonctionnalités que la version Pro', en: 'Fewer features than Pro version' },
    ],
    spaceRequired: 'Très Grand Studio',
    studioFootprint: { l: 600, w: 300, h: 292 },
  },
  {
    id: 'fashion-studio',
    nom: 'Fashion Studio Pro v2',
    prix: 84450,
    capaciteJour: 100,
    tailleMax: '200×100×200 cm (Espace scénique 3×3m)',
    poidsMax: '200 kg/m²',
    tailleCategories: ['grand', 'tres-grand'],
    useCases: ['Mode portée', 'Défilé vidéo', 'Stylisme complet'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 1500,
    dimensionsMax: { l: 200, w: 100, h: 200 },
    poidsMaxKg: 0, // Charge au m² plutôt qu'en kg fixe
    features: ['packshot', '360', 'video', 'ghost-mannequin', 'lifestyle'],
    automationLevel: 'semi-auto',
    idealSectors: ['fashion'],
    volumeRange: { min: 15000, max: 60000 },
    keyAdvantages: [
      { fr: 'Outils d\'interaction modèle (miroir virtuel, signaux)', en: 'Model interaction tools (virtual mirror, signals)' },
      { fr: 'Lumière Kick lights pour effets de mode', en: 'Kick lights for fashion effects' },
      { fr: 'Conçu spécifiquement pour flux vidéo/photo de mode', en: 'Specifically designed for fashion video/photo workflow' },
    ],
    limitations: [
      { fr: 'Encombrement très important (plus de 8m de long)', en: 'Very large footprint (over 8m long)' },
      { fr: 'Spécialisé mode, moins polyvalent pour packshot pur', en: 'Specialized for fashion, less versatile for pure packshot' },
    ],
    spaceRequired: 'Très Grand Studio',
    studioFootprint: { l: 847, w: 301, h: 292 },
  },
  {
    id: 'bike-studio',
    nom: 'Bike Studio',
    prix: 89450,
    capaciteJour: 70,
    tailleMax: '200×100×200 cm',
    poidsMax: '35 kg (point) / 200 kg (surface)',
    tailleCategories: ['tres-grand'],
    useCases: ['Vélos', 'Cycles', 'Trottinettes', 'Équipements cyclistes'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 1200,
    dimensionsMax: { l: 200, w: 100, h: 200 },
    poidsMaxKg: 35,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['cycling', 'sports'],
    volumeRange: { min: 3000, max: 20000 },
    keyAdvantages: [
      { fr: 'Système de suspension spécialisé pour vélos', en: 'Specialized suspension system for bikes' },
      { fr: '12 panneaux LED (190 000 lumens total)', en: '12 LED panels (190,000 lumens total)' },
      { fr: 'Support jusqu\'à 5 caméras simultanément', en: 'Support for up to 5 cameras simultaneously' },
    ],
    limitations: [
      { fr: 'Spécialisé vélos uniquement', en: 'Specialized for bikes only' },
      { fr: 'Encombrement important (~25m²)', en: 'Large footprint (~25m²)' },
    ],
    spaceRequired: 'Entrepôt',
    studioFootprint: { l: 847, w: 301, h: 292 },
  },
  {
    id: 'furniture-studio',
    nom: 'Furniture Studio',
    prix: 119450,
    capaciteJour: 60,
    tailleMax: 'Mobilier XXL',
    poidsMax: '500 kg',
    tailleCategories: ['tres-grand'],
    useCases: ['Canapés', 'Lits', 'Mobilier grande taille'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 2000,
    dimensionsMax: { l: 250, w: 200, h: 180 },
    poidsMaxKg: 500,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['furniture', 'appliances'],
    volumeRange: { min: 2000, max: 15000 },
    keyAdvantages: [
      { fr: 'Conçu spécifiquement pour le mobilier lourd', en: 'Specifically designed for heavy furniture' },
      { fr: 'Plateau haute capacité (500kg)', en: 'High capacity turntable (500kg)' },
      { fr: 'Éclairage optimisé pour grands volumes', en: 'Lighting optimized for large volumes' },
    ],
    limitations: [
      { fr: 'Investissement important', en: 'Significant investment' },
      { fr: 'Nécessite grand espace dédié', en: 'Requires large dedicated space' },
    ],
    spaceRequired: 'Entrepôt',
    studioFootprint: { l: 500, w: 400, h: 300 },
  },
  {
    id: 'e-comm-studio-plus',
    nom: 'E-Comm Studio+',
    prix: 150000,
    capaciteJour: 150,
    tailleMax: '300×300×200 cm',
    poidsMax: '1000 kg (4000 kg option)',
    tailleCategories: ['tres-grand'],
    useCases: ['Canapés', 'Meubles volumineux', 'Motos', 'Électroménager lourd'],
    maintenanceAnnuelle: 0,
    consommablesAnnuels: 2500,
    dimensionsMax: { l: 300, w: 300, h: 200 },
    poidsMaxKg: 1000,
    features: ['packshot', '360', 'video'],
    automationLevel: 'full-auto',
    idealSectors: ['furniture', 'appliances', 'automotive'],
    volumeRange: { min: 5000, max: 50000 },
    keyAdvantages: [
      { fr: 'Aucune limite de taille pour meubles standards', en: 'No size limit for standard furniture' },
      { fr: 'Plateau supportant 1 tonne (option 4 tonnes)', en: 'Turntable supporting 1 ton (4 ton option)' },
      { fr: 'Plateforme rotative 5m de diamètre', en: '5m diameter rotating platform' },
    ],
    limitations: [
      { fr: 'Nécessite espace et puissance électrique importants (9000W)', en: 'Requires significant space and electrical power (9000W)' },
      { fr: 'Investissement très élevé', en: 'Very high investment' },
    ],
    spaceRequired: 'Entrepôt',
    studioFootprint: { l: 670, w: 588, h: 302 },
  },
];

// Fonction helper pour trouver une machine par ID
export function getMachineById(id: string): Machine | undefined {
  return MACHINES.find(m => m.id === id);
}

// Fonction helper pour filtrer les machines par catégorie de taille
export function getMachinesBySize(category: ProductSizeCategory): Machine[] {
  return MACHINES.filter(m => m.tailleCategories.includes(category));
}

// Fonction helper pour filtrer les machines par feature
export function getMachinesByFeature(feature: Machine['features'][number]): Machine[] {
  return MACHINES.filter(m => m.features.includes(feature));
}

// Fonction helper pour filtrer les machines par secteur
export function getMachinesBySector(sector: Machine['idealSectors'][number]): Machine[] {
  return MACHINES.filter(m => m.idealSectors.includes(sector));
}
